# Generated by Django 3.2.12 on 2022-04-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_remove_artist_users'),
        ('account', '0002_alter_useraccount_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='artists',
            field=models.ManyToManyField(to='artist.Artist'),
        ),
    ]
