# Generated by Django 3.2.12 on 2022-04-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('account', '0003_useraccount_artists'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='tags',
            field=models.ManyToManyField(to='tag.Tag'),
        ),
    ]
