# Generated by Django 3.2.12 on 2022-04-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
        ('account', '0005_useraccount_liked_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='history',
            field=models.ManyToManyField(related_name='_account_useraccount_history_+', to='song.Song'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='liked_songs',
            field=models.ManyToManyField(related_name='_account_useraccount_liked_songs_+', to='song.Song'),
        ),
    ]
