# Generated by Django 3.2.12 on 2022-04-24 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20220422_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='history',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='liked_songs',
        ),
    ]
