# Generated by Django 3.2.12 on 2022-04-24 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
        ('account', '0009_usersonghistory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersonghistory',
            unique_together={('user', 'song')},
        ),
        migrations.AlterUniqueTogether(
            name='usersongliked',
            unique_together={('user', 'song')},
        ),
    ]
