# Generated by Django 3.2.12 on 2022-04-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_usersongliked_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='password_reset_token',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='password_reset_token_expiration',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
