# Generated by Django 3.2.12 on 2022-04-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_usersongcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersongcomment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
