# Generated by Django 3.2.12 on 2022-04-28 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('artist', '0004_remove_artist_users'),
        ('account', '0022_usersongpreferences'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSongPreferences',
            new_name='UserFavorites',
        ),
        migrations.AlterModelTable(
            name='userfavorites',
            table='user_song_favorites',
        ),
    ]
