# Generated by Django 3.2.12 on 2022-04-28 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20220428_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='artists',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='tags',
        ),
    ]
