# Generated by Django 3.2.12 on 2022-03-27 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('song_id', models.CharField(default=None, max_length=50)),
                ('song_name', models.CharField(max_length=220)),
                ('tag', models.TextField(default=None, max_length=200, null=True)),
                ('release_date', models.CharField(default=None, max_length=10)),
                ('creation_date', models.DateField(default=None)),
                ('duration', models.IntegerField(default=0)),
                ('danceability', models.FloatField(default=0)),
                ('acousticness', models.FloatField(default=0)),
                ('instrumentalness', models.FloatField(default=0)),
                ('valence', models.FloatField(default=0)),
                ('energy', models.FloatField(default=0)),
                ('speechiness', models.FloatField(default=0)),
                ('image', models.BinaryField(blank=True, editable=True, null=True)),
                ('url', models.TextField(blank=True, max_length=200, null=True)),
                ('spotify_uri', models.TextField(blank=True, max_length=200, null=True)),
                ('artist', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='artist.artist')),
                ('tags', models.ManyToManyField(to='tag.Tag')),
            ],
            options={
                'db_table': 'song',
            },
        ),
    ]
