# Generated by Django 3.2.12 on 2022-04-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='song_id',
            field=models.IntegerField(default=0),
        ),
    ]
