# Generated by Django 3.2.12 on 2022-05-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0003_likes_user_int_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='user_int_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
