# Generated by Django 3.2.12 on 2022-05-03 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0004_alter_likes_user_int_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='user_int_id',
        ),
    ]
