# Generated by Django 3.2.12 on 2022-05-04 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usersongrecommendation',
            table='recommendation',
        ),
    ]
